### ISSUE TITLE
[BUG]: playlists are not opening and playing the first video only

### ISSUE THREAD

**Issue by Hurchan** [yuliskov/SmartTube#4075] opened 2024-11-07 19:57 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

24.56

### Device Type

Smart TV/Box

### Affected Android

Android tv 11 shield

### Steps to reproduce the bug

Open any chanel.
Go to any playlist.
Open a playlist.
The playlist doesn't open and it plays the first video

**Comment by SkyNinja** [comment] 2024-11-07 21:01
I'm encountering the same issue.

**Comment by Skyline1023** [comment] 2024-11-07 21:28
Same issue. Can open my own personal playlists, but any playlists on a channel just starts playing videos in the playlist and I'm unable to select one.

**Comment by Dozo-MJK** [comment] 2024-11-07 22:43
Same issue on Firestick it displays the Playlist even with the "view playlist" text then it just opens the first video and does not play the rest of the playlist either.

**Comment by zukoju** [comment] 2024-11-07 23:36
Same issue on firestick, starting yesterday.

**Comment by sdragge** [comment] 2024-11-08 03:45
Just wanted to add a bit more info, I'm not programmer but it may help. I'm currently using a Chromecast, and when I hold down the selection button on a playlist, the sidebar that appears has the options:
>Add/Remove from subscription group
>Mark as watched.
>Open channel
>Add channel to sidebar.

Oddly enough, it seems to be combining options for videos and channels, and doesn't include the usual playlist options.

Hope the added detail helps 👍

**Comment by JJWilson-75** [comment] 2024-11-08 14:37
Same issue here

**Comment by Tobor8thMan** [comment] 2024-11-08 15:46
Same problem.  Tested on 3 different Onn 4K streaming boxes running Android 12.

**Comment by TorzAway** [comment] 2024-11-08 18:51
Same issue . . .        just plays first video in the playlist..  it started happening in 24.56 and is still present in today's push of 24.61

**Comment by JJWilson-75** [comment] 2024-11-09 02:33
Another potentially related isssue is I couldn't't find any playlist results in search, even after I tried to filter by playlist type

**Comment by SkyNinja** [comment] 2024-11-09 03:27
> Another potentially related issue is I couldn't find any playlist results in search, even after I tried to filter by playlist type

That one's actually been going on longer than this.

**Comment by TomyHtt26** [comment] 2024-11-09 06:35
Same issue here since at least 4 days on a Sony TV

**Comment by Fire-** [comment] 2024-11-09 07:33
Also seeing this on 24.37 stable ( alongside missing thumbnails ) and 24.61 beta ( with the thumbnail of the first video in the playlist )

**Comment by worador83** [comment] 2024-11-09 20:13
Same issue here, for a few days now. Both on my Fire TV stick and the Nokia streaming box, the playlist won’t open,only the first video plays.

**Comment by sdragge** [comment] 2024-11-09 22:05
(Update) Probably unnecessary, but I wanted to say the issue is resolved on my end with the latest update. Thank you for the prompt fix, the work is always appreciated. 👍

**Comment by Muffin1611** [comment] 2024-11-10 23:31
Same issue on my FireTV Stick.

**Comment by TomyHtt26** [comment] 2024-11-11 17:53
With the update installed right now the bug is fixed on Sony TV

**Comment by firelightrpg** [comment] 2024-11-11 20:17
> With the update installed right now the bug is fixed on Sony TV Thank you very much!!

There hasn't been any changes for this issue. I confirmed it is not fixed with 24.61 on a fire stick.

**Comment by SeongGino** [comment] 2024-11-11 20:19
> > With the update installed right now the bug is fixed on Sony TV Thank you very much!!
> 
> There hasn't been any changes for this issue. I confirmed it is not fixed with 24.61 on a fire stick.

I'm pretty sure they're talking about 24.64/24.65 Beta releases, which directly refers to this issue.

**Comment by firelightrpg** [comment] 2024-11-11 20:26
> I'm pretty sure they're talking about 24.64/24.65 Beta releases, which directly refers to this issue.
Can you link that issue here?

**Comment by mocduong2307** [comment] 2024-11-12 13:21
Same issue , i cant choose my video i want

**Comment by DaoSPBR** [comment] 2024-11-12 22:32
Same issue, Xiaomi MiBox and Firestick.

**Closed as completed** 2024-11-13 21:46 UTC
Labels: bug
