### ISSUE TITLE
[BUG]: App quits after each video

### ISSUE THREAD

**Issue by ryanhalley** [yuliskov/SmartTube#3845] opened 2024-08-20 23:26 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/yuliskov/SmartTube/issues) or [closed](https://github.com/yuliskov/SmartTube/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://github.com/yuliskov/SmartTube#faq) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

23.14

### Device Type

Smart TV/Box

### Affected Android

android tv 10

### Steps to reproduce the bug

1. Installed 23.14
2. Watched any video.

### Actual behavior

At end of video, app dumped me back to my previous app. The first time bounced me to Twitch. The second I first went to Home, then opened ST, watched a video, then kicked back to Home. The app is still listed in Apps so I think it is still running, and I can return to it but every video now quits at end.

### Additional information

Sony A95K
Have had no issues like this before.

**Comment by ryanhalley** [comment] 2024-08-20 23:28
I tried force quitting app, reloading it makes no difference.

**Comment by ryanhalley** [comment] 2024-08-20 23:34
I’ve found a workaround for now - I changed Playback mode from ‘Stop playback after one video’ to ‘Pause playback after each video’ - this doesn’t pause the video at the end, it drops me to the videos reel, but I can press Back twice afterwards to continue from where I started.

**Comment by MsKaboom** [comment] 2024-08-21 01:43
Same here, started after update to beta 23.14. Android tv on Nvidia shield. 
Also noticed my watch history isn't current after update.

**Comment by dakamc** [comment] 2024-08-21 03:51
Thirding this bug, new behavior for sure. Also on Nvidia Shield. I don't necessarily hate this behavior but it would be nice to have as an option if someone was thinking this would be implementable as a feature.

**Comment by ACR-Jeff** [comment] 2024-08-21 05:22
I just experienced this as well. Such a pain, Tried the "Pause playback after each video" method and it works for the time being, Yet another pain to deal with. Yet at least the app doesn't crash.

**Comment by ACR-Jeff** [comment] 2024-08-21 08:19
Latest 23.15 Beta fixed it for me. Thank you

**Comment by ryanhalley** [comment] 2024-08-21 08:39
Confirmed fixed in latest beta, cheers.

**Comment by ryanhalley** [comment] 2024-08-21 20:37
Regression. Reintroduced with 23.17

**Comment by ACR-Jeff** [comment] 2024-08-21 20:45
Closing my issue since this is re-opened 
https://github.com/yuliskov/SmartTube/issues/3849

Latest update 23.17 Beta Play video with "Stop playback after one video" will cause ST to crash after each video.
Prior version 23.15 Beta fixed this issue, Now it's back in 23.17 Beta

**Comment by MsKaboom** [comment] 2024-08-21 22:09
Same issue on beta 23.17

**Comment by hiroo916** [comment] 2024-08-21 22:57
Seeing this issue on 23.17 on nvidia shield

**Comment by plissken1138** [comment] 2024-08-21 23:30
Seeing this issue after 23.17 beta update, JVC smart TV.

**Comment by ACR-Jeff** [comment] 2024-08-22 00:07
The recent update 23.19 Beta seems to have fixed it on my end.

**Comment by plissken1138** [comment] 2024-08-22 00:32
Confirmed 23.19 beta update fixes it on JVC smart TV.

**Comment by MsKaboom** [comment] 2024-08-22 01:32
23.19 resolved it.  Thanks for your effort

**Closed** 2024-08-22 01:48 UTC
Labels: bug
